processors: '@mapbox/stylelint-processor-arbitrary-tags'
extends: stylelint-config-standard
rules:
  no-empty-source: null
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
      - global
